# Create network:configs:
# docker network create todo-net

services:
  gui:
    build:
      dockerfile: Dockerfile 
    container_name: todo-gui
    ports:
      - "3000:3000"
    environment:
      # https://stackoverflow.com/questions/76983550/neterr-name-not-resolved-in-browser-using-docker-compose
      # https://stackoverflow.com/questions/53237293/react-evironment-variables-env-return-undefined
      - REACT_APP_TODO_API_URL=http://172.27.0.2:1337/todo
      # - REACT_APP_TODO_API_URL=http://localhost:1337/todo
      # - REACT_APP_TODO_API_URL=http://todo-sails-app:1337/todo
    networks:
      - todo-net

networks:
  todo-net:
    external: true