# Create network:configs:
# docker network create todo-net

services:
  gui:
    build:
      dockerfile: Dockerfile
    container_name: todo-gui
    ports:
      - "3000:3000"
    environment:
     - REACT_APP_TODO_API_URL=https://localhost:1340/todo
     - REACT_APP_AUTH_API_URL=https://localhost:1340/auth
     # Make dev server work on windows
     - CHOKIDAR_USEPOLLING=true
     - WATCHPACK_POLLING=true
     
    networks:
      - todo-net
    volumes:
      - .:/usr/todo-app
networks:
  todo-net:
    external: true
