# Create network:configs:
# docker network create todo-net

services:
  gui:
    build:
      dockerfile: Dockerfile 
    container_name: todo-gui
    ports:
      - "3000:3000"
    env_file:
      - .env  
    networks:
      - todo-net

networks:
  todo-net:
    external: true