name: CI-development

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  prettier-eslint-unit-test:
    uses: ./.github/workflows/prettier-eslint-unit-test.yaml
